### ISSUE TITLE
Help, How to update NUI Skeleton?

### ISSUE THREAD

**Issue by jonike** [AleDel/KinectXbox360-UE4#1]
Hello, Sir. 
How to Update Skeleton Stream and get Joints Positions from Ue4 engine in blueprints editor.
![20171107183254](https://user-images.githubusercontent.com/7898256/32489271-598d5dc4-c3ea-11e7-9422-aecc4cd32b71.jpg)

Thanks.

**Comment by AleDel** [comment]
hello, I have not yet modified the rotation of the bones of the character satisfactorily. but if it is useful, I attach a capture of how to use the position of the bones in some instances of an object.

![kinect_instantiate](https://user-images.githubusercontent.com/690648/32594081-730b63de-c522-11e7-886e-2425814b5ea2.jpg)

**Comment by AleDel** [comment]
hi, here the example (extract inside Content folder)
[Kinect_Skel.zip](https://github.com/AleDel/KinectXbox360-UE4/files/1463520/Kinect_Skel.zip)

![kinect_bones](https://user-images.githubusercontent.com/690648/32687208-93ff193a-c6af-11e7-91dc-2350e6a15d84.jpg)
