### ISSUE TITLE
Problem including the plugin to existing project

### ISSUE THREAD

**Issue by damien220** [AleDel/KinectXbox360-UE4#6]
Dear Sir,
Thank you for the plugin and i would like to ask for help in using this plugin.
I am using ue4.23, i am creating a new cpp empty project, and then i create the Plugins folder and copy your plugin ( the while folder as suggested) to Plugins folder.
When i lunch the project, i get this error: "XboxKinectPlugin could not be compiled.Try rebuilding from source manually".
(XboxKinectPlugin, is the name of the project i created).
I would like to ask if this plugin is only compatible with specific ue4 version?If yes, what are those versions?
If no, how can i solve my problem?Knowing that when i build the source code in VS, i am getting plenty of error in the code.
I hope you answer the question as soon as possible because i really need to try this plugin.
And thank you.
Edit:
I am using kinect v1.

**Comment by adrianperezferro** [comment]
I had the same issues. You have to edit the plugin. On KinectManager.h you should edit this line: #include "HideWindowsPlatformTypes.h" to #include "Windows/HideWindowsPlatformTypes.h" and on KiectModule.h #include "ModuleManager.h" to #include "Modules/ModuleManager.h". Also ensure you have installed Visual Studio Code 2019 and Net Framework.

**Comment by damien220** [comment]
Hi @adrianperezferro , thank you for the reply....Well problem not solved, and my kinet project is dead so i am dropping it.
Thank you anyway,
